#!/bin/bash

set -e

poe="`pwd`"

dir=/tmp/poe-app-ui-$RANDOM
echo $dir
mkdir -p $dir

cleanup() {
  rm -rf $dir
}

trap 'cleanup' EXIT

cd $dir

POE_UI=$poe $poe/bin/poe-ui-create <<EOF
my-test-app
This is a description
poe-app
EOF


$poe/test/cli/smoke-test $poe/test/cli/smoke-test.js
